# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a0653885d8b4f00587c1dce38b9be398accb467f8f98ed9b66d6e144f39c84813445dcccffbc8eda0183bfe17cf13303cd6b6c083626b994e9e67d5f6f4c97

test:
  secret_key_base: 5a0da990afe43c8f4072b5fe5f71b92c04c9f328db80a2b23132587910f30d052d51fcdbabe4cf7119d6372a36d71047fb16f6e859811e7552b1d917f0793d30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
